### ISSUE TITLE
Hypixel Zombies Pack Compatibility

### ISSUE THREAD

**Issue by TheGreatDeimo** [opekope2/OptiGUI#119]
### Expected Behavior

The GUI modification in this pack (found here: https://hypixel.net/threads/hypixel-zombies-custom-resource-pack-with-sounds.5381117/) does not work without using OptiFine. I'm not entirely sure what the issue is because I'm not versed in resource packs. The image shows what is supposed to change, but I'm not seeing that. There may be other things that I'm missing.
![image_2024-10-15_214452654](https://github.com/user-attachments/assets/80ec4dd0-e2af-4b18-b5a3-c6b7079ad3ad)

### Actual Behavior

While most if not all other features in the pack seem to be working, the hud replacement is not.

### Steps To Reproduce

Download the pack and run it.

### Loader and its version

Fabric loader 0.16.5

### OptiGUI version

2.3.0-beta.6 for 1.21

### Behavior difference

- [ ] OptiGUI documentation
- [ ] OptiFine
- [X] Something you logically expect from OptiGUI
- [ ] Doesn't work at all

### Anything else

I'm not 100% sure this belongs here, but I don't know where else it would go. My bad if so.

**Comment by opekope2** [comment]
> All textures containing multiple sprites in a sheet for GUI have been split into individual sprites under textures/gui/sprites (automated by Slicer tool).

`/assets/minecraft/textures/gui/widgets.png` is no longer used [since Minecraft 1.20.2 (scroll down to "resource packs")](https://minecraft.wiki/w/Java_Edition_1.20.2#General_2). This is a resource pack issue, not OptiGUI, OptiFine, or another mod issue.
The resource pack if for Minecraft 1.19. Mojang started to update resource pack format basically every snapshot since then.
