### ISSUE TITLE
Crash on startup 1.18.2

### ISSUE THREAD

**Issue by wati2006** [opekope2/OptiGUI#33]
The mod is crashing on 1.18.2 since the version 2.0.0-alpha.6
Here's a crash log: https://mclo.gs/vyFBiCp

**Comment by opekope2** [comment]
Oh, boi. I overlooked something. I placed chest boats inside OptiGUI instead of OptiGlue (which obviously crashes, because it's non-existent). However, as of #32, this part of the code will be rewritten. Until that, you should downgrade to **v1.1.6**, 2.0.0-alpha.4, or 2.0.0-alpha.5.

The documentation matches the 2.0.0-alpha.6.

It was a bit tricky to find line 103, when a file is only 89 lines long.

I'll mark the affected versions as 1.18-unsupported on Modrinth and CurseForge.
