### ISSUE TITLE
[CRASH] Kotlin update crashes OptiGUI

### ISSUE THREAD

**Issue by Madis0** [opekope2/OptiGUI#80]
### Loader and its version

Fabric Loader 0.14.24

### OptiGUI version

2.1.6

### Steps to reproduce

1. Have OptiGUI
2. Update Fabric Language Kotlin to 1.10.11

### Game logs

https://mclo.gs/xgogMt1

### Anything else

The instance is Fabulously Optimized 5.5.0-beta.3, but the presence of other mods is currently irrelevant here. Works on Fabric Language Kotlin 1.10.10.

**Comment by viridivn** [comment]
Issue also occurs with Fabric Language Kotlin 1.10.11

**Comment by opekope2** [comment]
For some reason, OptiGUI is loaded with the default language adapter before FLK 1.10.11, and it works, but on 1.10.11, it is loaded with the Kotlin adapter, which has a bug; top level function references don't work. After looking at the git blame, it never worked. I don't know what got changed that now the Kotlin adapter gets loaded instead of the default one. I'll open an issue in the Kotlin adapter repo about this.

Loading with FLK 1.9.0:

![image](https://github.com/opekope2/OptiGUI/assets/20487556/2985945d-7da9-452c-a150-a41a2e4bb50b)

Loading with FLK 1.10.11:

![image](https://github.com/opekope2/OptiGUI/assets/20487556/6434e040-32b0-4374-9c15-3838333a7d2d)

Update: this rabbit hole goes deeper than I thought. Caused by a Kotlin Reflection change.

**Comment by MeeniMc** [comment]
Workaround: roll back to Fabric Kotlin 1.10.10.

**Comment by modmuss50** [comment]
This is now fixed in Fabric Kotlin 1.10.12.
